using Xamarin.Forms;

namespace ImmunoApp
{
    /// <summary>
    /// App class. Entry for staring the application
    /// Author: Auto-generated by Xamarin
    /// </summary>
	public partial class App : Application
	{
        /// <summary>
        /// Constructor. Sets the Mainpage to the first ContentPage
        /// </summary>
        public App ()
		{
			InitializeComponent();
            MainPage = new Login();
		}

		protected override void OnStart ()
		{
			// Handle when your app starts
		}

		protected override void OnSleep ()
		{
			// Handle when your app sleeps
		}

		protected override void OnResume ()
		{
			// Handle when your app resumes
		}
	}
}
